export const TEAMS = [
  {
    id: 'barca11',
    name: 'FC Barcelona',
    year: '2010/11',
    emoji: '🔵',
    bg: 'rgba(0,80,200,0.12)',
    rating: 97,
    type: 'club',
    era: '2010s',
    ability: 'Тікі-така: при програші тактики, наступний ПАС раунд +15',
    star: 'Messi',
    players: [
      { n: 'Messi',  pos: 'НАП', stat: 97 },
      { n: 'Villa',  pos: 'НАП', stat: 88 },
      { n: 'Pedro',  pos: 'НАП', stat: 82 },
      { n: 'Xavi',   pos: 'ЦП',  stat: 94 },
      { n: 'Puyol',  pos: 'ЦЗ',  stat: 91 },
      { n: 'Valdes', pos: 'ВРТ', stat: 85 },
    ],
  },
  {
    id: 'milan03',
    name: 'AC Milan',
    year: '2002/03',
    emoji: '🔴',
    bg: 'rgba(220,30,30,0.12)',
    rating: 94,
    type: 'club',
    era: '2000s',
    ability: 'Фортеця Мальдіні: перший гол суперника не зараховується',
    star: 'Shevchenko',
    players: [
      { n: 'Shevchenko', pos: 'НАП', stat: 93 },
      { n: 'Inzaghi',    pos: 'НАП', stat: 86 },
      { n: 'Rui Costa',  pos: 'ЦП',  stat: 88 },
      { n: 'Maldini',    pos: 'ЦЗ',  stat: 95 },
      { n: 'Nesta',      pos: 'ЦЗ',  stat: 92 },
      { n: 'Dida',       pos: 'ВРТ', stat: 87 },
    ],
  },
  {
    id: 'real02',
    name: 'Real Madrid',
    year: '2001/02',
    emoji: '⚪',
    bg: 'rgba(180,180,180,0.1)',
    rating: 96,
    type: 'club',
    era: '2000s',
    ability: 'Галактикос: зірка команди +20 в першому раунді',
    star: 'Zidane',
    players: [
      { n: 'Zidane',        pos: 'ЦП', stat: 98 },
      { n: 'Raul',          pos: 'НАП', stat: 90 },
      { n: 'Figo',          pos: 'ПАП', stat: 91 },
      { n: 'Roberto Carlos',pos: 'ЛБ',  stat: 90 },
      { n: 'Hierro',        pos: 'ЦЗ',  stat: 87 },
      { n: 'Casillas',      pos: 'ВРТ', stat: 91 },
    ],
  },
  {
    id: 'manutd99',
    name: 'Man United',
    year: '1998/99',
    emoji: '🔴',
    bg: 'rgba(200,0,0,0.1)',
    rating: 93,
    type: 'club',
    era: '90s',
    ability: 'Камбек Фергюсона: при 0:2 всі атрибути +10',
    star: 'Beckham',
    players: [
      { n: 'Beckham',    pos: 'ПП',  stat: 90 },
      { n: 'Scholes',    pos: 'ЦП',  stat: 89 },
      { n: 'Yorke',      pos: 'НАП', stat: 88 },
      { n: 'Cole',       pos: 'НАП', stat: 87 },
      { n: 'Stam',       pos: 'ЦЗ',  stat: 91 },
      { n: 'Schmeichel', pos: 'ВРТ', stat: 95 },
    ],
  },
  {
    id: 'brazil70',
    name: 'Бразилія',
    year: 'ЧС 1970',
    emoji: '🟡',
    bg: 'rgba(255,200,0,0.1)',
    rating: 99,
    type: 'national',
    era: '90s',
    ability: 'Самба: рандомний гравець +25 кожен раунд',
    star: 'Pelé',
    players: [
      { n: 'Pelé',         pos: 'НАП', stat: 99 },
      { n: 'Rivelino',     pos: 'ЛП',  stat: 91 },
      { n: 'Jairzinho',    pos: 'ПАП', stat: 90 },
      { n: 'Tostão',       pos: 'НАП', stat: 88 },
      { n: 'Carlos Alberto',pos: 'ПБ', stat: 88 },
      { n: 'Félix',        pos: 'ВРТ', stat: 80 },
    ],
  },
  {
    id: 'inter10',
    name: 'Inter Milan',
    year: '2009/10',
    emoji: '🖤',
    bg: 'rgba(100,80,200,0.1)',
    rating: 93,
    type: 'club',
    era: '2010s',
    ability: 'Мурінью: тактика завжди перемагає незалежно від схеми',
    star: 'Sneijder',
    players: [
      { n: 'Sneijder',    pos: 'ЦП',  stat: 92 },
      { n: 'Milito',      pos: 'НАП', stat: 90 },
      { n: "Eto'o",       pos: 'НАП', stat: 91 },
      { n: 'Zanetti',     pos: 'ПБ',  stat: 88 },
      { n: 'Lucio',       pos: 'ЦЗ',  stat: 88 },
      { n: 'Julio Cesar', pos: 'ВРТ', stat: 88 },
    ],
  },
  {
    id: 'france98',
    name: 'Франція',
    year: 'ЧС 1998',
    emoji: '🇫🇷',
    bg: 'rgba(0,30,180,0.1)',
    rating: 95,
    type: 'national',
    era: '90s',
    ability: 'Зізу-ефект: Зідан отримує +15 у вирішальному раунді',
    star: 'Zidane',
    players: [
      { n: 'Zidane',       pos: 'ЦП',  stat: 96 },
      { n: 'Thierry Henry',pos: 'НАП', stat: 89 },
      { n: 'Platini',      pos: 'ЦП',  stat: 91 },
      { n: 'Desailly',     pos: 'ЦЗ',  stat: 88 },
      { n: 'Thuram',       pos: 'ПБ',  stat: 87 },
      { n: 'Barthez',      pos: 'ВРТ', stat: 88 },
    ],
  },
  {
    id: 'bayern13',
    name: 'Bayern Munich',
    year: '2012/13',
    emoji: '🔴',
    bg: 'rgba(220,20,20,0.1)',
    rating: 95,
    type: 'club',
    era: '2010s',
    ability: 'Pressing: захист завжди дорівнює атаці суперника -10',
    star: 'Ribéry',
    players: [
      { n: 'Ribéry', pos: 'ЛП',  stat: 91 },
      { n: 'Robben', pos: 'ПП',  stat: 91 },
      { n: 'Müller', pos: 'НАП', stat: 89 },
      { n: 'Lahm',   pos: 'ПБ',  stat: 91 },
      { n: 'Boateng',pos: 'ЦЗ',  stat: 89 },
      { n: 'Neuer',  pos: 'ВРТ', stat: 95 },
    ],
  },
];

export const ROUNDS = [
  { key: 'attack',  name: 'АТАКА',     emoji: '⚔️', hint: 'Обери гравця для атаки. Найвищий атрибут перемагає.' },
  { key: 'defense', name: 'ЗАХИСТ',    emoji: '🛡️', hint: 'Обери захисника. Якщо твій захист вищий — блокуєш гол.' },
  { key: 'set',     name: 'СТАНДАРТИ', emoji: '🎯', hint: 'Штрафний або кутовий. Точність вирішує все.' },
  { key: 'tactics', name: 'ТАКТИКА',   emoji: '🧠', hint: 'Вибери схему гри. Камінь-ножиці-папір стилю.' },
  { key: 'penalty', name: 'ПЕНАЛЬТІ',  emoji: '🥅', hint: 'Серія пенальті. Вибери виконавця.' },
];
